### ISSUE TITLE
floor() seems to behave probabilistically.

### ISSUE THREAD

**Issue by tshead2** [cicada-mpc/cicada-mpc#10]
... more so than I would expect.  The results are frequently off-by-one-bit, sometimes to the left and sometimes to the right of the decimal point.  For example, the following result from the documentation should return 3.0:

```
INFO:root:Player 0 secret: 3.5
INFO:root:Player 1 secret: 3.5
INFO:root:Player 2 secret: 3.5
INFO:root:Player 0 floor: 4.0
INFO:root:Player 1 floor: 4.0
INFO:root:Player 2 floor: 4.0
```

Many more examples at https://cicada-mpc.readthedocs.io/en/latest/user-guide/floor.html

**Comment by kgoss1729** [comment]
Take a look at the new function floor_bit_dec(). We'll change the name later i've been messing with different ways to do floor and naming the functions related to the method used. It's called in a similar way to floor in test_floor.ipynb. I need to generalize the function to work on arbitrary shape arrays, but it appears to have much better accuracy.

**Comment by kgoss1729** [comment]
Addressed with new approach based on bit decomposition in https://github.com/cicada-mpc/cicada-mpc/commit/57b074957c9bda913704ee5a7f78fb5af5464917
