### ISSUE TITLE
AdditiveProtocol.exp() should be renamed public_private_power()

### ISSUE THREAD

**Issue by tshead2** [cicada-mpc/cicada-mpc#12]
Also: it should also accept an array of exponents instead of a single value, for consistency with the rest of the API?

**Comment by kgoss1729** [comment]
Addressed in https://github.com/cicada-mpc/cicada-mpc/commit/84d88461fc27c6d6d7e162e65c1a098e1bf8c509 

I made it "private_public_power" instead of "public_private_power" since the base is the first argument and is what is private while the exponent is public and is the second argument
