### ISSUE TITLE
Explain probabilistic results.

### ISSUE THREAD

**Issue by tshead2** [cicada-mpc/cicada-mpc#5]
For example, the division article states "Our method here is dependent on our integer division which is approximate and this method is therefore probabilistic."

Need to document this more thoroughly, possibly in a standalone topic.

**Comment by kgoss1729** [comment]
Added some explanation and a brief example in a user guide notebook https://github.com/cicada-mpc/cicada-mpc/commit/31fd8068eb6c9f31db8ea338566a2bfb7a354334
