### ISSUE TITLE
Add dot() methods to ActiveProtocol and ShamirProtocol.

### ISSUE THREAD

**Issue by tshead2** [cicada-mpc/cicada-mpc#55]

**Comment by kgoss1729** [comment]
Added in https://github.com/cicada-mpc/cicada-mpc/commit/afa3fb4df766e38396498cf584bd28a49703d4db I also added an argument to the example script to make testing this easier. Calling it like: python examples/dot.py -p shamir will run it with the ShamirProtocol object and -p active with the ActiveProtocol object.
