### ISSUE TITLE
Remove the current ActiveArrayShare.__getitem__() implementation.

### ISSUE THREAD

**Issue by tshead2** [cicada-mpc/cicada-mpc#68]
... it's currently being used by the implementation to access internal storage, but we need to reserve the API for array-slicing operations instead.

**Comment by kgoss1729** [comment]
ב''ה
Greetings,

If I understand the desired use correctly for __getitem__ then calling active_shared_thing[0] should return a valid active array share for the first element in whatever active_shared_thing was?

שלום וברכה
Peace and Blessing,

Ken Goss, Ph.D.
Sandia National Laboratories
All-Source Analytics Dept., 5552
Location: 750/222
Office: 505-284-3182<tel:1284-3182>
Cell: 417-718-5404
***@***.******@***.***>

From: Timothy M. Shead ***@***.***>
Sent: Thursday, October 6, 2022 10:29 AM
To: cicada-mpc/cicada-mpc ***@***.***>
Cc: Goss, Ken ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [cicada-mpc/cicada-mpc] Remove the current ActiveArrayShare.__getitem__() implementation. (Issue #68)


... it's currently being used by the implementation to access internal storage, but we need to reserve the API for array-slicing operations instead.

**Comment by tshead2** [comment]
That is one case among many, but I wasn't expecting you to implement it now; the main thing is for the rest of the protocol implementation to use some other mechanism to access the underlying additive and shamir storage.

**Comment by kgoss1729** [comment]
I was right there and not too difficult, so I went for it. For accessing the others I added @property decorators to access additive_subshare and shamir_subshare object instances. I am happy to change those if you prefer other terminology, but I thought it was ok for a first pass anyway.

In other news I just ran more than a thousand instances of active private divide without incident. Doing some other final testing to make sure that I haven't inadvertently broken anything else in my tinkering and that will be pushed and sorted.

From: Timothy M. Shead ***@***.***>
Sent: Tuesday, October 11, 2022 10:11 AM
To: cicada-mpc/cicada-mpc ***@***.***>
Cc: Goss, Ken ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [cicada-mpc/cicada-mpc] Remove the current ActiveArrayShare.__getitem__() implementation. (Issue #68)


That is one case among many, but I wasn't expecting you to implement it now; the main thing is for the rest of the protocol implementation to use some other mechanism to access the underlying additive and shamir storage.

-

**Comment by kgoss1729** [comment]
Fixed in bd2f0f66a15b987ff169b8c6dab8319620fcf53b
