### ISSUE TITLE
Split encoders into separate field arithmetic and encoding objects.

### ISSUE THREAD

**Issue by tshead2** [cicada-mpc/cicada-mpc#72]
**The Good**

"Field arithmetic" objects would only implement arithmetic, and would be used as an internal implementation detail by protocol suites.  "Encodings" would only convert between domain values and field values, and would be chosen by callers.  Protocol suite `share` and `reveal` methods would use default encodings, but would allow the default to be overridden with an optional argument.  This would eliminate the need for `share_bits`, `reveal_bits`, and `reveal_field`, and is comparable to Python string operations that take optional encoding arguments.  The default encoding could be specified in a protocol suite's initializer; a sensible choice would be our current 16-bit fixed-point representation.  A special "identity" encoding would allow library users to work directly with field values if they prefer.

This would also eliminate current and future problems with operations such as `private_public_power` and `public_private_subtract` - that require encoded arguments, causing the caller to use the deprecated encoder property.

**The Bad**

Allowing callers to specify the encoding for individual `share` and `reveal` calls makes it possible to mix encodings in incompatible ways since e.g. the precision for fixed point representations is no longer part of the protocol state.

*Counterargument:* To implement our compatibility property for protocol suite instances, the caller already has to keep track of parameters like "precision", so asking them to do the same for encoding parameters isn't really any different. 

**The Ugly (Not Really)**

Removing the encoding precision from the protocol state has knock-on ramifications for mathematical operations.  In a nutshell, it forces us to make an explicit distinction between "encoding-aware" and "encoding-agnostic" ops.  For example, `floor` and `truncate` are operations that intuitively need to know the encoding precision (perhaps `truncate` should be renamed `right_shift` while we're at it?).  `divide`, `dot`, `multiply`, and `public_private_power` are encoding-aware since they rely on `truncate`.  `untruncated_divide` does too, but we need to talk about it.  `private_public_power`, `untruncated_private_public_divide`, and `zigmoid` need to create encoded values in their implementation.

**Comment by kgoss1729** [comment]
This makes a lot of sense to me, and I think would make the overall consistency and uniformity of the library better and more intuitive.

**Comment by tshead2** [comment]
There is a partial implementation in the `encodings` branch.

**Comment by tshead2** [comment]
Closed in ae8a9764b55516bf7dcf9dedec8b65230f1da6a6
