### ISSUE TITLE
Possible to persist secret-shared values and resume computation later?

### ISSUE THREAD

**Issue by matthiasgeihs** [cicada-mpc/cicada-mpc#81]
Hi again, sorry for the numerous questions/comments... I like the library and currently experimenting with it, that's why...

This one is actually more like a feature request:
Is it currently possible to persist secret-shared values, shut down the program, and then later load the secret-shared values and continue the computation?

**Comment by matthiasgeihs** [comment]
Seems like we can just use pickle to write and read secret shares to and from disk.

**Comment by tshead2** [comment]
@matthiasgeihs: I had never contemplated this, but pickling would be my first choice.  If you need some other format, you could also access the `storage` properties of `ActiveArrayShare`, `AdditiveArrayShare`, or `ShamirArrayShare`, which are explicitly provided for serialization.

Cheers,
Tim
